Fix a warning on an older compiler
GCC8 generates the following warning when compiling smsdb.c
```
smsdb.c: In function 'smsdb_outgoing_part_status':
smsdb.c:713:18: error: 'uid' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  if (res >= 0 && smsdb_outgoing_clear_nolock(uid) < 0) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

As far as I can tell, it's wrong - there is no way res can be >= 0 and uid remain uninitialized
but it seems that GCC8 is not as good at escape analysis.

Nevertheless, GCC8 is still being used by OpenWRT and this change to placate it is simple enough.

Signed-off-by: Deomid "rojer" Ryabkov <rojer@rojer.me>